-- =====================================================================
-- PHCL Asset Intake -- organisation units
-- GENERATED by scripts/genseed.ps1 from the Beetrack master templates.
-- Source workbook: 4. department-template-file.xlsx
-- Do not hand-edit; change the workbook or the script and re-run.
-- =====================================================================
insert into am_org (code, name_vi, name_en, level, is_company, is_department, parent_code, note) values
  ('PHCL', 'Công ty TNHH Liên Doanh Khách Sạn Plaza', 'Plaza Hotel Ltd.', 'TCT', true, true, null, null),
  ('JVC', 'Văn phòng đại diện chủ đầu tư', 'JVC Office', 'BRANCH', true, true, 'PHCL', null),
  ('CP', 'Cao ốc văn phòng Central Plaza', 'Central Plaza', 'BRANCH', true, true, 'PHCL', null),
  ('CEN', 'Bộ phận vận hành Cao ốc văn phòng Central Plaza', 'Central Plaza Department', 'DEPT1', true, true, 'CP', null),
  ('SOF', 'Khách sạn Sofitel SG Plaza', 'Sofitel Saigon Plaza', 'BRANCH', true, true, 'PHCL', null),
  ('FOD', 'Bộ phận tiền sảnh', 'Front Office Department', 'DEPT1', false, true, 'SOF', null),
  ('HKD', 'Bộ phận quản gia', 'House Keeping Department', 'DEPT1', false, true, 'SOF', null),
  ('FBD', 'Bộ phận F&B', 'Food & Beverage Department', 'DEPT1', false, true, 'SOF', null),
  ('KIT', 'Bộ phận bếp', 'Kitchen Department', 'DEPT1', false, true, 'SOF', null),
  ('ENG', 'Bộ phận kỹ thuật', 'Engineering Department', 'DEPT1', false, true, 'SOF', null),
  ('ADM', 'Bộ phận hành chính, nhân sự', 'Administration & Human Resource Department', 'DEPT1', false, true, 'SOF', null),
  ('SMD', 'Bộ phận quảng cáo, bán hàng', 'Sale & Marketing Department', 'DEPT1', false, true, 'SOF', null),
  ('FIN', 'Bộ phận tài chính, kế toán', 'Finance Department', 'DEPT1', false, true, 'SOF', null),
  ('ITD', 'Bộ phận IT', 'IT Department', 'DEPT1', false, true, 'SOF', null),
  ('SEC', 'Bộ phận an ninh', 'Security Department', 'DEPT1', false, true, 'SOF', null)
on conflict (code) do update
  set name_vi = excluded.name_vi, name_en = excluded.name_en, level = excluded.level,
      is_company = excluded.is_company, is_department = excluded.is_department,
      parent_code = excluded.parent_code;

-- Aliases: other files in the company spell some codes differently.
insert into am_org_alias (alias, code, source) values
  ('HKP', 'HKD', 'Beetrack "4. Org Code" / "1. Area Code" / KiemKe-HKP'),
  ('IT',  'ITD', 'Beetrack "4. Org Code" / KiemKe-IT'),
  ('Security', 'SEC', 'Beetrack "1. Area Code"'),
  ('S&M', 'SMD', 'KiemKe-S&M'),
  ('A&G', 'ADM', 'KiemKe-A&G (Administration & General)')
on conflict (alias) do update set code = excluded.code, source = excluded.source;
