-- =====================================================================
-- PHCL Asset Intake -- asset categories
-- GENERATED by scripts/genseed.ps1 from the Beetrack master templates.
-- Source workbook: 3. category-template-file.xlsx
-- Do not hand-edit; change the workbook or the script and re-run.
-- =====================================================================
insert into am_category_group (code, name_vi, name_en, is_intangible, is_tools, sort_order) values
  ('C2111', 'Nhà cửa, vật kiến trúc', 'Buildings and structures', false, false, 10),
  ('C2112', 'Máy móc và thiết bị', 'Machinery and equipment', false, false, 20),
  ('C2113', 'Trang thiết bị và phương tiện vận tải', 'Transportation and transmission vehicles', false, false, 30),
  ('C2114', 'Thiết bị, công cụ quản lý', 'Office equipment, management toos', false, false, 40),
  ('C2115', 'Cây lâu năm, súc vật làm việc và cho sản phẩm', 'Perennial trees, Working and Producing Animals', false, false, 50),
  ('C2118', 'Tài sản cố định hữu hình khác', 'Other tangible asset', false, false, 60),
  ('C2131', 'Quyền sử dụng đất', 'Land use rights', true, false, 70),
  ('C2132', 'Quyền phát hành', 'Copyrights', true, false, 80),
  ('C2133', 'Bản quyền, quyền phát hành, bằng sáng chế', 'Patent', true, false, 90),
  ('C2134', 'Nhãn hiệu độc quyền, tên thương mại, quyền sở hữu trí tuệ', 'Trademarks, trade names', true, false, 100),
  ('C2135', 'Chương trình, phần mềm', 'Computer software', true, false, 110),
  ('C2136', 'Giấy phép và giấy phép nhượng quyền', 'License and right concession permits', true, false, 120),
  ('C2138', 'Tài sản cố định vô hình khác', 'Other intangible asset', true, false, 130),
  ('C2421', 'Thiết bị, CCDC ngắn hạn (không đủ điều kiện ghi nhận TSCĐ)', 'Short-term tools & supplies', false, true, 140),
  ('C2422', 'Thiết bị, CCDC dài hạn (không đủ điều kiện ghi nhận TSCĐ)', 'Long-term tools & supplies', false, true, 150)
on conflict (code) do update
  set name_vi = excluded.name_vi, name_en = excluded.name_en,
      is_intangible = excluded.is_intangible, is_tools = excluded.is_tools;

-- label_letters = the code with the -QR suffix removed; LTG and LTG-QR both
-- print as "LTG", which is why they must share one sequence.
-- manage_by: 'code' = one record per unit, 'quantity' = grouped by count.
insert into am_category (code, group_code, name_vi, name_en, label_letters, manage_by, note) values
  ('BUL', 'C2111', 'Tòa nhà', 'Building', 'BUL', 'code', null),
  ('STR', 'C2111', 'Công trình, kiến trúc khác', 'Other structure', 'STR', 'code', null),
  ('INF', 'C2111', 'Cơ sở hạ tầng kỹ thuật', 'Infrastructure, Constructual item', 'INF', 'code', null),
  ('MES', 'C2112', 'Hệ thống điện và cơ khí', 'Machenical & Electrical Systems', 'MES', 'code', null),
  ('FFP', 'C2112', 'Thiết bị, hệ thống PCCC', 'Fire Fighting & Prevention Equipment/System', 'FFP', 'code', null),
  ('ITO', 'C2112', 'Thiết bị công nghệ thông tin sử dụng cho việc kinh doanh', 'Information Technology Equipment for operation', 'ITO', 'code', null),
  ('KME', 'C2112', 'Thiết bị, vật dụng bếp', 'Kitchen Machinery & Equipment', 'KME', 'code', null),
  ('FUR', 'C2112', 'Thiết bị, vật dụng nội thất', 'Furniture, artworks', 'FUR', 'code', null),
  ('SME', 'C2112', 'Máy móc, thiết bị vệ sinh', 'Sanitary Machinery & Equipment', 'SME', 'code', null),
  ('OME', 'C2112', 'Máy móc, thiết bị khác', 'Other Machinery & Equiment', 'OME', 'code', null),
  ('TTV', 'C2113', 'Trang thiết bị và phương tiện vận tải', 'Transportation and transmission vehicles', 'TTV', 'code', null),
  ('ITM', 'C2114', 'Thiết bị công nghệ thông tin sử dụng cho việc quản trị', 'Information Technology Equipment for management', 'ITM', 'code', null),
  ('OEM', 'C2114', 'Thiết bị, vật dụng, công cụ khác sử dụng cho mục đích quản lý.', 'Other Funitures, Equipments, Measurement tools for management purposes.', 'OEM', 'code', null),
  ('PWP', 'C2115', 'Cây lâu năm, súc vật làm việc và cho sản phẩm', 'Perennial trees, Working and Producing Animals', 'PWP', 'code', null),
  ('OTA', 'C2118', 'Tài sản cố định hữu hình khác', 'Other tangible asset', 'OTA', 'code', null),
  ('LUR', 'C2131', 'Quyền sử dụng đất', 'Land use rights', 'LUR', 'code', null),
  ('CPR', 'C2132', 'Quyền phát hành', 'Copyrights', 'CPR', 'code', null),
  ('PAT', 'C2133', 'Bản quyền, quyền phát hành, bằng sáng chế', 'Patent', 'PAT', 'code', null),
  ('TMK', 'C2134', 'Nhãn hiệu độc quyền, tên thương mại, quyền sở hữu trí tuệ', 'Trademarks, trade names', 'TMK', 'code', null),
  ('CTP', 'C2135', 'Chương trình, phần mềm', 'Computer software', 'CTP', 'code', null),
  ('LRP', 'C2136', 'Giấy phép và giấy phép nhượng quyền', 'License and right concession permits', 'LRP', 'code', null),
  ('OIA', 'C2138', 'Tài sản cố định vô hình khác', 'Other intangible asset', 'OIA', 'code', null),
  ('STU', 'C2421', 'Thiết bị, CCDC ngắn hạn (không đủ điều kiện ghi nhận TSCĐ)', 'Short-term tools & supplies', 'STU', 'code', null),
  ('LTU', 'C2422', 'Thiết bị, CCDC dài hạn (không đủ điều kiện ghi nhận TSCĐ)', 'Long-term tools & supplies', 'LTU', 'code', null),
  ('STG', 'C2421', 'Thiết bị, CCDC ngắn hạn (không đủ điều kiện ghi nhận TSCĐ) - Khác QR', 'Short-term tools & supplies', 'STG', 'quantity', 'A separate QR label per unit ("Khac QR").'),
  ('LTG', 'C2422', 'Thiết bị, CCDC dài hạn (không đủ điều kiện ghi nhận TSCĐ) - Khác QR', 'Long-term tools & supplies', 'LTG', 'quantity', 'A separate QR label per unit ("Khac QR").'),
  ('LTG-QR', 'C2422', 'Thiết bị, CCDC dài hạn (không đủ điều kiện ghi nhận TSCĐ) - Cùng QR', 'Long-term tools & supplies', 'LTG', 'quantity', 'One shared QR label for the whole batch ("Cung QR").'),
  ('STG-QR', 'C2421', 'Thiết bị, CCDC dài hạn (không đủ điều kiện ghi nhận TSCĐ) - Cùng QR', 'Long-term tools & supplies', 'STG', 'quantity', 'One shared QR label for the whole batch ("Cung QR").')
on conflict (code) do update
  set group_code = excluded.group_code, name_vi = excluded.name_vi,
      name_en = excluded.name_en, label_letters = excluded.label_letters,
      manage_by = excluded.manage_by, note = excluded.note;
