-- =====================================================================
-- PHCL Asset Intake -- units of measure
-- GENERATED by scripts/genseed.ps1 from the Beetrack master templates.
-- Source workbook: 10. unit-template-file.xlsx
-- Do not hand-edit; change the workbook or the script and re-run.
-- =====================================================================
insert into am_unit (code, name_vi, name_en, sort_order) values
  ('litre', null, 'Litre', 10),
  ('kwh', null, 'Kilowatt-hour (kwh)', 20),
  ('kg', null, 'kg', 30),
  ('m3', null, 'Cubic Meter (m3)', 40),
  ('pcs', null, 'pcs', 50),
  ('m', null, 'm', 60),
  ('set', null, 'set', 70),
  ('box', null, 'box', 80),
  ('m2', null, 'm2', 90),
  ('package', null, 'package', 100),
  ('time', null, 'time', 110),
  ('room', null, 'room', 120),
  ('floor', null, 'floor', 130),
  ('pot', null, 'pot', 140),
  ('tubes', null, 'tubes', 150),
  ('lit', null, 'Liter (lit)', 160)
on conflict (code) do update set name_en = excluded.name_en, sort_order = excluded.sort_order;
