param(
  [string]$Src = "C:\Users\huynh\OneDrive - Cong ty TNHH Lien doanh Khach san Plaza\Khanh\Asset Management System\Asset Management System\Sinnova - Amis - Beetrack\Template Beetrack_PHCL",
  [string]$OutDir = "$PSScriptRoot\..\sql"
)

# Generates the master-data seed files from the six authoritative Beetrack
# templates. Run this instead of hand-editing sql/02*.sql.
#
# KEEP THIS FILE PURE ASCII (see the note in serve.ps1): PowerShell 5.1 reads a
# BOM-less .ps1 as ANSI, and a stray UTF-8 dash then breaks the whole script.
# All Vietnamese text comes from the workbooks at runtime, never from here.

. "$PSScriptRoot\xl.ps1"

$OutDir = (Resolve-Path $OutDir).Path
$files = @{
  cat    = '3. category-template-file.xlsx'
  dept   = '4. department-template-file.xlsx'
  loc    = '6. location-template-file.xlsx'
  prod   = '8. product-catalogue-template-file.xlsx'
  origin = '9. origin-country-template-file.xlsx'
  unit   = '10. unit-template-file.xlsx'
}
foreach ($k in $files.Keys) {
  if (-not (Test-Path -LiteralPath (Join-Path $Src $files[$k]))) { throw "Missing $($files[$k]) in $Src" }
}
function P($k) { Join-Path $Src $files[$k] }

# ---- helpers ---------------------------------------------------------------
function Q($t) {
  if ($null -eq $t -or $t -eq '') { return 'null' }
  return "'" + ($t -replace "'", "''") + "'"
}
# Turn "R12|A12=x|C12=y|" into a hashtable keyed by column letter.
function Cells($line) {
  $h = @{}
  foreach ($m in [regex]::Matches($line, '([A-Z]+)\d+=([^|]*)')) {
    $h[$m.Groups[1].Value] = $m.Groups[2].Value.Trim()
  }
  return $h
}
function Rows($path, $sheet, $max = 20000) {
  Dump-Sheet $path $sheet $max | Select-Object -Skip 1 | ForEach-Object { Cells $_ }
}
function Header($title, $source) {
  @"
-- =====================================================================
-- PHCL Asset Intake -- $title
-- GENERATED by scripts/genseed.ps1 from the Beetrack master templates.
-- Source workbook: $source
-- Do not hand-edit; change the workbook or the script and re-run.
-- =====================================================================

"@
}
$out = @{}

# ---- 1. departments (am_org) ----------------------------------------------
$dept = Rows (P 'dept') 'worksheets/sheet1.xml'
$dept = $dept | Where-Object { $_['B'] }
$byCode = @{}; foreach ($d in $dept) { $byCode[$d['B']] = $d }
function Depth($code) {
  $n = 0; $c = $code
  while ($c -and $byCode[$c] -and $byCode[$c]['C']) { $c = $byCode[$c]['C']; $n++; if ($n -gt 6) { break } }
  return $n
}
$levelOf = @{ 0 = 'TCT'; 1 = 'BRANCH'; 2 = 'DEPT1'; 3 = 'DEPT2'; 4 = 'DEPT2' }
# Codes that appear as "Ma Cong Ty Thanh Vien" on real asset rows.
$companies = @('PHCL', 'JVC', 'CP', 'CEN', 'SOF')

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append((Header 'organisation units' $files['dept']))
[void]$sb.Append(@"
insert into am_org (code, name_vi, name_en, level, is_company, is_department, parent_code, note) values

"@)
$rows = @()
foreach ($d in $dept) {
  $code = $d['B']; $parent = $d['C']; $en = $d['D']; $vi = $d['F']
  if (-not $vi) { $vi = $en }
  $rows += "  ({0}, {1}, {2}, {3}, {4}, true, {5}, null)" -f `
    (Q $code), (Q $vi), (Q $en), (Q $levelOf[[int](Depth $code)]),
    $(if ($companies -contains $code) { 'true' } else { 'false' }), (Q $parent)
}
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (code) do update
  set name_vi = excluded.name_vi, name_en = excluded.name_en, level = excluded.level,
      is_company = excluded.is_company, is_department = excluded.is_department,
      parent_code = excluded.parent_code;

-- Aliases: other files in the company spell some codes differently.
insert into am_org_alias (alias, code, source) values
  ('HKP', 'HKD', 'Beetrack "4. Org Code" / "1. Area Code" / KiemKe-HKP'),
  ('IT',  'ITD', 'Beetrack "4. Org Code" / KiemKe-IT'),
  ('Security', 'SEC', 'Beetrack "1. Area Code"'),
  ('S&M', 'SMD', 'KiemKe-S&M'),
  ('A&G', 'ADM', 'KiemKe-A&G (Administration & General)')
on conflict (alias) do update set code = excluded.code, source = excluded.source;
"@)
$out['org'] = $sb.ToString()

# ---- 2. categories ---------------------------------------------------------
$cat = Rows (P 'cat') 'worksheets/sheet1.xml' | Where-Object { $_['B'] }
$groups = @{}; $types = @()
foreach ($c in $cat) {
  if ($c['G'] -eq '2') { if (-not $groups.ContainsKey($c['B'])) { $groups[$c['B']] = $c } }
  else { $types += $c }
}
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append((Header 'asset categories' $files['cat']))
[void]$sb.Append("insert into am_category_group (code, name_vi, name_en, is_intangible, is_tools, sort_order) values`n")
$rows = @(); $i = 0
foreach ($k in ($groups.Keys | Sort-Object)) {
  $g = $groups[$k]; $i += 10
  $intang = if ($k -match '^C213') { 'true' } else { 'false' }
  $tools = if ($k -match '^C242') { 'true' } else { 'false' }
  $rows += "  ({0}, {1}, {2}, {3}, {4}, {5})" -f (Q $k), (Q $g['D']), (Q $g['E']), $intang, $tools, $i
}
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (code) do update
  set name_vi = excluded.name_vi, name_en = excluded.name_en,
      is_intangible = excluded.is_intangible, is_tools = excluded.is_tools;

-- label_letters = the code with the -QR suffix removed; LTG and LTG-QR both
-- print as "LTG", which is why they must share one sequence.
-- manage_by: 'code' = one record per unit, 'quantity' = grouped by count.
insert into am_category (code, group_code, name_vi, name_en, label_letters, manage_by, note) values

"@)
$rows = @()
foreach ($c in $types) {
  $code = $c['B']; $letters = $code -replace '-QR', ''
  $manage = if ($code -match '^(STG|LTG)') { 'quantity' } else { 'code' }
  $note = if ($code -like '*-QR') { 'One shared QR label for the whole batch ("Cung QR").' }
          elseif ($manage -eq 'quantity') { 'A separate QR label per unit ("Khac QR").' }
          else { $null }
  $rows += "  ({0}, {1}, {2}, {3}, {4}, {5}, {6})" -f `
    (Q $code), (Q $c['C']), (Q $c['D']), (Q $c['E']), (Q $letters), (Q $manage), (Q $note)
}
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (code) do update
  set group_code = excluded.group_code, name_vi = excluded.name_vi,
      name_en = excluded.name_en, label_letters = excluded.label_letters,
      manage_by = excluded.manage_by, note = excluded.note;
"@)
$out['cat'] = $sb.ToString()

# ---- 3. units --------------------------------------------------------------
$unit = Rows (P 'unit') 'worksheets/sheet1.xml' | Where-Object { $_['B'] }
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append((Header 'units of measure' $files['unit']))
[void]$sb.Append("insert into am_unit (code, name_vi, name_en, sort_order) values`n")
$rows = @(); $i = 0
foreach ($u in $unit) { $i += 10; $rows += "  ({0}, null, {1}, {2})" -f (Q $u['B']), (Q $u['A']), $i }
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (code) do update set name_en = excluded.name_en, sort_order = excluded.sort_order;
"@)
$out['unit'] = $sb.ToString()

# ---- 4. origins ------------------------------------------------------------
$org2 = Rows (P 'origin') 'worksheets/sheet1.xml' | Where-Object { $_['A'] -match '^[A-Z]{2}$' }
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append((Header 'countries of origin (ISO 3166-1 alpha-2)' $files['origin']))
[void]$sb.Append("insert into am_origin (iso2, name_en) values`n")
$rows = @()
foreach ($o in $org2) { $rows += "  ({0}, {1})" -f (Q $o['A']), (Q $o['B']) }
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (iso2) do update set name_en = excluded.name_en;

-- Vietnamese names for the countries that actually turn up in purchasing files.
update am_origin set name_vi = v.vi from (values
  ('VN','Viet Nam'),('CN','Trung Quoc'),('JP','Nhat Ban'),('KR','Han Quoc'),
  ('TW','Dai Loan'),('TH','Thai Lan'),('MY','Malaysia'),('SG','Singapore'),
  ('ID','Indonesia'),('PH','Philippines'),('IN','An Do'),('US','My'),
  ('GB','Anh'),('DE','Duc'),('FR','Phap'),('IT','Y'),('ES','Tay Ban Nha'),
  ('NL','Ha Lan'),('BE','Bi'),('CH','Thuy Si'),('SE','Thuy Dien'),('AT','Ao'),
  ('PL','Ba Lan'),('TR','Tho Nhi Ky'),('RU','Nga'),('AU','Uc'),('NZ','New Zealand'),
  ('CA','Canada'),('MX','Mexico'),('BR','Brazil'),('HK','Hong Kong'),('MO','Ma Cao'),
  ('KH','Campuchia'),('LA','Lao'),('MM','Myanmar'),('AE','UAE'),('DK','Dan Mach'),
  ('NO','Na Uy'),('FI','Phan Lan'),('PT','Bo Dao Nha'),('CZ','Sec'),('IL','Israel')
) as v(code, vi) where am_origin.iso2 = v.code;

-- Aliases: ONLY when the text names exactly ONE country.
-- alias_norm must be the output of am_norm(): lowercase, no diacritics.
insert into am_origin_alias (alias_norm, iso2, note) values
  ('usa','US',null),('u.s.a','US',null),('u.s.a.','US',null),('us','US',null),
  ('united states','US',null),('america','US',null),('my','US','"My" with diacritics stripped'),
  ('viet nam','VN',null),('vietnam','VN',null),('vn','VN',null),
  ('china','CN',null),('p.r.c','CN',null),('prc','CN',null),('trung quoc','CN',null),
  ('chinese','CN',null),('made in china','CN',null),
  ('uk','GB',null),('england','GB',null),('great britain','GB',null),
  ('united kingdom','GB',null),('anh','GB',null),
  ('korea','KR',null),('south korea','KR',null),('han quoc','KR',null),('kr','KR',null),
  ('japan','JP',null),('nhat ban','JP',null),('jp','JP',null),
  ('taiwan','TW',null),('dai loan','TW',null),('tw','TW',null),
  ('thailand','TH',null),('thai lan','TH',null),
  ('malaysia','MY',null),('singapore','SG',null),('indonesia','ID',null),
  ('germany','DE',null),('duc','DE',null),('deutschland','DE',null),
  ('france','FR',null),('phap','FR',null),
  ('italy','IT',null),('italia','IT',null),('y','IT',null),
  ('spain','ES',null),('netherlands','NL',null),('holland','NL',null),
  ('switzerland','CH',null),('turkey','TR',null),('turkiye','TR',null),
  ('russia','RU',null),('australia','AU',null),('canada','CA',null),
  ('india','IN',null),('an do','IN',null),
  ('hong kong','HK',null),('hongkong','HK',null),
  ('uae','AE',null),('united arab emirates','AE',null),
  ('czech','CZ',null),('czech republic','CZ',null),('brasil','BR',null)
on conflict (alias_norm) do update set iso2 = excluded.iso2, note = excluded.note;

-- Strings deliberately NOT mapped, so the interface can say why it is blank.
insert into am_origin_rejected (raw_norm, raw_sample, reason) values
  ('asia','Asia','not_a_country'),
  ('eu','EU','not_a_country'),
  ('europe','Europe','not_a_country'),
  ('asean','ASEAN','not_a_country'),
  ('imported','Imported','not_a_country'),
  ('nhap khau','Nhap khau','not_a_country'),
  ('oem','OEM','not_a_country'),
  ('n/a','N/A','not_a_country')
on conflict (raw_norm) do nothing;
"@)
$out['origin'] = $sb.ToString()

# ---- 5. locations ----------------------------------------------------------
# Sheet 1 "Group&Trackable": C = code, D = parent, E = name, B = 1 building / 2 floor
# Sheet 2 "Internal":        C = code, B = parent, D = name  -> rooms
$loc = @()
foreach ($r in (Rows (P 'loc') 'worksheets/sheet1.xml')) {
  if (-not $r['C']) { continue }
  $loc += [pscustomobject]@{ code = $r['C']; parent = $r['D']; name = $r['E']
                             kind = $(if ($r['B'] -eq '1') { 'building' } else { 'floor' }) }
}
foreach ($r in (Rows (P 'loc') 'worksheets/sheet2.xml')) {
  if (-not $r['C']) { continue }
  $loc += [pscustomobject]@{ code = $r['C']; parent = $r['B']; name = $r['D']; kind = 'room' }
}
# One default office per department, matched on the location name only.
# "Talent & Culture" is the hotel's name for HR, so it maps to ADM
# (Administration & Human Resource Department) -- inferred, worth confirming.
# FOD is deliberately absent: the location list has no "Front office".
$officeByName = @{
  'It office' = 'ITD'; 'Finance office' = 'FIN'
  'Security office' = 'SEC'; 'Housekeeping office' = 'HKD'; 'F&B office' = 'FBD'
  'Sale office' = 'SMD'; 'Talent & Culture office' = 'ADM'; 'Kitchen office' = 'KIT'
  'Engineering office' = 'ENG'
}
$usedDept = @{}
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append((Header 'locations (buildings, floors, rooms)' $files['loc']))
[void]$sb.Append("insert into am_location (code, name, kind, parent_code, dept_code, is_dept_office) values`n")
$rows = @()
foreach ($l in $loc) {
  # NB: do not name this $dept -- that would shadow the department list above.
  $owner = $null
  foreach ($n in $officeByName.Keys) {
    if ($l.name -and $l.name.Trim().ToLower() -eq $n.ToLower() -and -not $usedDept[$officeByName[$n]]) {
      $owner = $officeByName[$n]; $usedDept[$owner] = $true; break
    }
  }
  $rows += "  ({0}, {1}, {2}, {3}, {4}, {5})" -f `
    (Q $l.code), (Q $l.name), (Q $l.kind), (Q $l.parent), (Q $owner),
    $(if ($owner) { 'true' } else { 'false' })
}
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (code) do update
  set name = excluded.name, kind = excluded.kind, parent_code = excluded.parent_code;
"@)
$out['loc'] = $sb.ToString()

# ---- 6. product catalogue --------------------------------------------------
# C = category code, D = "Ten Viet/English name", F = brand, H = unit.
# raw_name_norm is computed by am_norm() in Postgres so it always matches the
# key the application looks products up by.
$prod = Rows (P 'prod') 'worksheets/sheet1.xml' | Where-Object { $_['D'] }
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append((Header 'product catalogue' $files['prod']))
[void]$sb.Append("insert into am_product (raw_name_norm, raw_name, std_name_vi, std_name_en, default_category, default_unit, default_brand) values`n")
$rows = @(); $seen = @{}
foreach ($p in $prod) {
  $full = $p['D']
  if ($seen[$full.ToLower()]) { continue }
  $seen[$full.ToLower()] = $true
  $i = $full.IndexOf('/')
  $vi = if ($i -gt 0) { $full.Substring(0, $i).Trim() } else { $full }
  $en = if ($i -gt 0) { $full.Substring($i + 1).Trim() } else { $null }
  $rows += "  (am_norm({0}), {0}, {1}, {2}, {3}, {4}, {5})" -f `
    (Q $full), (Q $vi), (Q $en), (Q $p['C']), (Q $p['H']), (Q $p['F'])
}
[void]$sb.Append(($rows -join ",`n"))
[void]$sb.Append(@"

on conflict (raw_name_norm) do update
  set raw_name = excluded.raw_name, std_name_vi = excluded.std_name_vi,
      std_name_en = excluded.std_name_en, default_category = excluded.default_category,
      default_unit = excluded.default_unit, default_brand = excluded.default_brand;
"@)
$out['prod'] = $sb.ToString()

# ---- write -----------------------------------------------------------------
$enc = New-Object System.Text.UTF8Encoding $false
$plan = @{
  '02a_seed_org.sql'      = $out['org']
  '02b_seed_category.sql' = $out['cat']
  '02c_seed_unit.sql'     = $out['unit']
  '02d_seed_origin.sql'   = $out['origin']
  '02e_seed_location.sql' = $out['loc']
  # Numbered 06 on purpose: it calls am_norm(), which only exists once
  # 03_functions.sql has run.
  '06_seed_product.sql'   = $out['prod']
}
foreach ($f in $plan.Keys) {
  [System.IO.File]::WriteAllText((Join-Path $OutDir $f), $plan[$f] + "`n", $enc)
}
"org       {0,5} rows" -f $dept.Count
"groups    {0,5} rows" -f $groups.Count
"types     {0,5} rows" -f $types.Count
"units     {0,5} rows" -f $unit.Count
"origins   {0,5} rows" -f $org2.Count
"locations {0,5} rows" -f $loc.Count
"products  {0,5} rows" -f $seen.Count
"dept offices matched: {0}" -f (($usedDept.Keys | Sort-Object) -join ', ')
